'use client'

import { useState } from 'react'
import { ArrowUpRight, BarChart3, Bell, BookOpen, CalendarDays, Check, ChevronDown, CircleHelp, FilePlus2, FolderOpen, Hash, Image as ImageIcon, Instagram, LayoutDashboard, Lightbulb, Menu, PenLine, Search, Settings, Sparkles, TrendingUp, X } from 'lucide-react'

const navItems = [
  ['Inicio', LayoutDashboard], ['Publicaciones', PenLine], ['Biblioteca', FolderOpen],
  ['Calendario', CalendarDays], ['Ideas', Lightbulb], ['Rendimiento', BarChart3],
] as const
const posts = [
  { time: '09:00', title: 'Ramo de cumpleaños', category: 'Florería', tags: 'cumpleaños · rosas · regalo', last: 'Hace 21 días', color: 'bg-[#e8c8a9]' },
  { time: '13:30', title: '¿Tu computadora está lenta?', category: 'Tecnología', tags: 'reparación · limpieza', last: 'Hace 15 días', color: 'bg-[#c4d9d2]' },
  { time: '19:00', title: 'Visa americana por primera vez', category: 'Visa', tags: 'DS-160 · asesoría', last: 'Hace 26 días', color: 'bg-[#d7c9e8]' },
]

export function DashboardShell() {
  const [active, setActive] = useState('Inicio')
  const [menuOpen, setMenuOpen] = useState(false)
  const [generated, setGenerated] = useState(false)
  const [published, setPublished] = useState<string[]>([])
  const go = (label: string) => { setActive(label); setMenuOpen(false) }
  return <div className="min-h-screen bg-[#f5f5f1] text-[#1f2422]">
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[248px] flex-col border-r border-[#dedfd8] bg-[#f8f8f4] px-5 py-6 transition-transform lg:translate-x-0 ${menuOpen ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="mb-10 flex items-center justify-between px-2"><div className="flex items-center gap-2.5"><div className="flex size-8 items-center justify-center rounded-xl bg-[#222824] text-[#f5c86a]"><Sparkles className="size-4" /></div><span className="font-serif text-xl font-semibold">norte.</span></div><button aria-label="Cerrar menú" className="lg:hidden" onClick={() => setMenuOpen(false)}><X /></button></div>
      <p className="px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#949a93]">Espacio de trabajo</p>
      <nav className="mt-3 flex flex-col gap-1" aria-label="Principal">{navItems.map(([label, Icon]) => <button key={label} onClick={() => go(label)} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm ${active === label ? 'bg-[#e8ebe3] font-medium' : 'text-[#777e77] hover:bg-[#eef0eb]'}`}><Icon className="size-[17px]" />{label}</button>)}</nav>
      <div className="my-7 h-px bg-[#e1e2dc]" /><p className="px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#949a93]">Cuenta</p>
      <nav className="mt-3 flex flex-col gap-1" aria-label="Cuenta">{['Conexiones', 'Configuración'].map((label) => <button key={label} onClick={() => go(label)} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm ${active === label ? 'bg-[#e8ebe3] font-medium' : 'text-[#777e77] hover:bg-[#eef0eb]'}`}><Settings className="size-[17px]" />{label}</button>)}</nav>
      <div className="mt-auto rounded-2xl bg-[#e9eee5] p-4"><div className="mb-3 flex size-8 items-center justify-center rounded-full bg-[#f5c86a] text-[#67501b]"><CircleHelp className="size-4" /></div><p className="text-sm font-medium">¿Necesitas una mano?</p><p className="mt-1 text-xs leading-5 text-[#747b72]">Aprende a automatizar tus anuncios.</p></div>
    </aside>
    {menuOpen && <button aria-label="Cerrar menú" className="fixed inset-0 z-30 bg-black/20 lg:hidden" onClick={() => setMenuOpen(false)} />}
    <main className="lg:ml-[248px]"><header className="flex h-[76px] items-center justify-between border-b border-[#dedfd8] bg-[#f8f8f4]/80 px-5 backdrop-blur-md sm:px-8"><button aria-label="Abrir menú" className="lg:hidden" onClick={() => setMenuOpen(true)}><Menu /></button><div className="hidden items-center gap-2 text-sm text-[#7a8179] sm:flex">Espacio de trabajo <ChevronDown className="size-4" /></div><div className="ml-auto flex items-center gap-3"><button aria-label="Buscar" className="rounded-full p-2 text-[#7d847c]"><Search /></button><button aria-label="Notificaciones" className="rounded-full p-2 text-[#7d847c]"><Bell /></button><div className="flex items-center gap-2 border-l border-[#dedfd8] pl-3"><div className="flex size-8 items-center justify-center rounded-full bg-[#d5ddd2] text-xs font-semibold">AM</div><span className="hidden text-sm font-medium sm:block">Ana Martín</span></div></div></header>
      <div className="mx-auto max-w-[1400px] px-5 py-8 sm:px-8 lg:px-10 lg:py-10"><div className="mb-9 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-2 text-sm text-[#8a9188]">Martes, 23 de septiembre de 2026</p><h1 className="font-serif text-4xl tracking-tight sm:text-5xl">Buenos días, Ana<span className="text-[#c18d32]">.</span></h1><p className="mt-3 text-sm leading-6 text-[#747b72]">Estas son tus publicaciones recomendadas para hoy.</p></div><button onClick={() => setGenerated(true)} className="flex w-fit items-center gap-2 rounded-xl bg-[#222824] px-4 py-3 text-sm font-medium text-white"><Sparkles className="size-4 text-[#f5c86a]" />{generated ? 'Publicaciones generadas' : 'Generar publicaciones de hoy'}</button></div>
        <section className="grid gap-5 xl:grid-cols-[1.35fr_0.65fr]"><div className="rounded-3xl bg-[#222824] p-6 text-white sm:p-8"><div className="mb-5 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.17em] text-[#adb9ac]"><Sparkles className="size-3.5 text-[#f5c86a]" />Recomendado para hoy</div><h2 className="max-w-lg font-serif text-3xl leading-tight sm:text-4xl">Hoy te conviene publicar contenido de florería.</h2><p className="mt-4 max-w-md text-sm leading-6 text-[#b4bdb4]">Hace 4 días que no publicas esta categoría, tuvo el mejor rendimiento de la semana y tienes 12 anuncios disponibles sin usar recientemente.</p><button onClick={() => setGenerated(true)} className="mt-8 flex items-center gap-2 rounded-xl bg-[#f5c86a] px-4 py-2.5 text-sm font-semibold text-[#3c321c]">Ver recomendaciones <ArrowUpRight className="size-4" /></button></div><div className="rounded-3xl border border-[#dedfd8] bg-[#fbfbf8] p-6 sm:p-7"><p className="text-sm text-[#7f877e]">Rendimiento de ayer</p><p className="mt-2 text-3xl font-semibold">+24.8%</p><div className="mt-7 flex h-14 items-end gap-1.5">{[28,38,31,54,42,64,49,72,63,88,70,96].map((height, i) => <div key={i} className={`flex-1 rounded-t-sm ${i > 8 ? 'bg-[#6e9d79]' : 'bg-[#c6ddca]'}`} style={{ height: `${height}%` }} />)}</div><div className="mt-3 flex justify-between text-[11px] text-[#9aa198]"><span>Alcance total</span><span>12.4k personas</span></div></div></section>
        <section className="mt-8 grid gap-8 xl:grid-cols-[1.35fr_0.65fr]"><div><div className="mb-4"><h2 className="font-serif text-2xl">Publicaciones de hoy</h2><p className="mt-1 text-sm text-[#858c84]">Anuncios seleccionados para evitar repeticiones.</p></div><div className="overflow-hidden rounded-2xl border border-[#dedfd8] bg-[#fbfbf8]">{posts.map((post, i) => { const done = published.includes(post.title); return <div key={post.time} className={`flex items-center gap-4 px-4 py-4 sm:px-5 ${i < posts.length - 1 ? 'border-b border-[#e5e6e0]' : ''}`}><span className="w-12 text-xs text-[#959b93]">{post.time}</span><div className={`size-11 shrink-0 rounded-xl ${post.color}`}><ImageIcon className="mx-auto mt-3 size-5 text-[#6c716b]/50" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{post.title}</p><p className="mt-1 text-xs text-[#929990]">{post.category} · {post.tags}</p><p className="mt-1 text-[11px] text-[#b0b5ae]">Última publicación: {post.last}</p></div><button onClick={() => setPublished(done ? published.filter((x) => x !== post.title) : [...published, post.title])} className={`hidden rounded-lg px-2.5 py-2 text-xs font-medium sm:block ${done ? 'bg-[#e2eee5] text-[#518060]' : 'text-[#65705f] hover:bg-[#eef0eb]'}`}>{done ? <Check className="size-4" /> : 'Marcar publicada'}</button><button aria-label={`Editar ${post.title}`} className="rounded-lg p-2 text-[#929990]"><PenLine className="size-4" /></button></div> })}</div></div><div><div className="mb-4 flex items-center justify-between"><div><h2 className="font-serif text-2xl">Ideas nuevas</h2><p className="mt-1 text-sm text-[#858c84]">Basadas en tu contenido y rendimiento.</p></div><Lightbulb className="size-5 text-[#c18d32]" /></div><div className="flex flex-col gap-3">{['Crear promoción de flores amarillas', 'Publicación educativa sobre errores en visa', 'Oferta de reparación de computadoras'].map((idea, i) => <button key={idea} className="flex items-center gap-3 rounded-2xl border border-[#dedfd8] bg-[#fbfbf8] p-4 text-left"><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-[#f1e6c9] text-xs font-semibold text-[#87682b]">0{i + 1}</span><span className="flex-1 text-sm font-medium leading-5">{idea}</span><ArrowUpRight className="size-4 text-[#a1a79f]" /></button>)}</div></div></section>
        <section className="mt-8 rounded-3xl border border-[#dedfd8] bg-[#fbfbf8] p-6 sm:p-7"><div className="mb-6"><h2 className="font-serif text-2xl">Rendimiento de tus anuncios</h2><p className="mt-1 text-sm text-[#858c84]">Lo que mejor funciona en Facebook e Instagram.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Mejor categoría', 'Florería', '+38% interacción'], ['Mejor horario', '6:00 PM', '+21% alcance'], ['Red con más interacción', 'Instagram', '64% del engagement'], ['Alcance total', '12.4k', '+24.8% esta semana']].map(([label, value, note]) => <div key={label} className="rounded-2xl bg-[#eef3eb] p-4"><p className="text-xs text-[#7d877a]">{label}</p><p className="mt-2 flex items-center gap-1 font-semibold">{value === 'Instagram' && <Instagram className="size-4" />}{value}</p><p className="mt-1 text-xs text-[#518060]">{note}</p></div>)}</div></section>
        <section className="mt-10 grid gap-4 sm:grid-cols-3"><button onClick={() => setGenerated(true)} className="flex items-center gap-3 rounded-2xl border border-dashed border-[#c8ccc4] p-4 text-left"><FilePlus2 className="size-5 text-[#778476]" /><span><strong className="block text-sm">Crear anuncio</strong><small className="text-xs text-[#929990]">Genera copy con IA</small></span></button><button onClick={() => go('Biblioteca')} className="flex items-center gap-3 rounded-2xl border border-dashed border-[#c8ccc4] p-4 text-left"><BookOpen className="size-5 text-[#778476]" /><span><strong className="block text-sm">Explorar biblioteca</strong><small className="text-xs text-[#929990]">Imágenes, tags y anuncios</small></span></button><button onClick={() => go('Conexiones')} className="flex items-center gap-3 rounded-2xl border border-dashed border-[#c8ccc4] p-4 text-left"><Hash className="size-5 text-[#778476]" /><span><strong className="block text-sm">Conectar Meta</strong><small className="text-xs text-[#929990]">Facebook e Instagram</small></span></button></section>
      </div></main>
  </div>
}
